source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'app-ios' do
  # MultiPlatformLibrary
  # для корректной установки фреймворка нужно сначала скомпилировать котлин библиотеку - compile-kotlin-framework.sh (в корневой директории репозитория)
  pod 'MultiPlatformLibrary', :path => '../app-common'
  pod 'MultiPlatformLibraryRpm', :path => '../'
  # pod 'MultiPlatformLibraryRpm', :git => 'https://github.com/vchernyshov/reaktive-pm.git', :tag => 'release/0.1.0-beta'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'SkyFloatingLabelTextField', '3.8.0'
end
